# Generated by Django 3.2.7 on 2021-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_category_computer_compcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
