# Generated by Django 3.2.7 on 2021-10-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_computer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compcategory',
            options={'verbose_name_plural': 'compcategories'},
        ),
        migrations.AddField(
            model_name='computer',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
